services:
  postgres:
    image: postgres
  rabbit:
    image: rabbitmq:management
    ports:
    - "15672:15672"
  worker:
    build:
      context: .
      dockerfile: WorkerService/Dockerfile
  projection:
    build:
      context: .
      dockerfile: ProjectionWorker/Dockerfile
  api1:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
    - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
